server:
  port: 8081

spring:
  application:
    name: userService
#devtools 配置
#  devtools:
#    restart:
#      quiet-period: 3000
#      poll-interval: 4000

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/docker_db?serverTimeZone=UTC&useUnicode=true@characterEncoding=utf-8
    username: root
    password: 123456
    driverName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registerWithEureka: true
    fetchRegistry: true