server:
  port: 8181

spring:
  application:
    name: orderService

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/docker_db?serverTimeZone=UTC&useUnicode=true@characterEncoding=utf-8
    username: root
    password: 123456
    driverName: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka