

spring:
  application:
    name: eurekaserver


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registerWithEureka: false
    fetchRegistry: false



server:
  port: 10086